version: "2.4"
services:
  test:
    build: .
    runtime: nvidia
    volumes:
      - $PWD:/working
    container_name: mnist
    working_dir: /working
    ports:
      - 8080:8080
    environment:
      - PYTHONPATH=/working
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true