common:
    seed: &seed 2020
    metrics:
        name: accuracy
        params: {}
    drop:
    kaggle:
        submit: False

model:
    backbone: resnext50_32x4d
    n_channels: 1
    n_classes: &class 10
    epochs: &epoch 20
    params: 
        pretrained: True
    multi_gpu: True
    avgpool:
        name: GeM
        params: {}
    head:
        linear:
            name: Linear
            params:
                in_features: 2048
                out_features: *class

validation:
    name: KFold
    params:
        n_splits: 5
        random_state: *seed
    split:
        y: label
        groups:
    weight:
        - 0.2
    single: True

data:
    train:
        dataset_type: CustomDataset
        img_size:
            width: &wsize 56
            height: &hsize 56
        loader:
            shuffle: True
            batch_size: 128
            num_workers: 4
        transforms:
            rotate:
                name: Rotate
                params:
                    p: 0.5
                    limit: 10
    valid:
        dataset_type: CustomDataset
        img_size:
            width: *wsize
            height: *hsize
        loader:
            shuffle: False
            batch_size: 128
            num_workers: 4
        transforms:
        tta:
            iter_num: 1
    test:
        dataset_type: CustomDataset
        img_size:
            width: *wsize
            height: *hsize
        loader:
            shuffle: False
            batch_size: 128
            num_workers: 4
        transforms:
        tta:
            iter_num: 1

loss: 
    name: CrossEntropyLoss
    params: {}

optimizer:
    name: SGD
    params:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0001

scheduler:
    name: CosineAnnealingLR
    params:
        eta_min: 0.00001
        T_max: *epoch